### ISSUE TITLE
Doesn't support IE8 and under

### ISSUE THREAD

**Issue by notasausage** [Abban/jQuery-Picture#1]
This is already documented, but jQuery Picture doesn't work with Internet Explorer 8 or under due to the fact that these older versions of IE have no support for media queries. That said, there are other scripts written to add this support specifically, including:

Respond by Scott Jehl
https://github.com/scottjehl/Respond

css3-mediaqueries-js by Wouter van der Graaf
http://code.google.com/p/css3-mediaqueries-js/

Combining one of these with jQuery Picture would probably do the trick.

**Comment by Abban** [comment]
I did the IE testing this morning and found a couple of bugs in there. The plugin now works in IE7/8/9. I think I'm gonna leave out forcing media queries in IE7 and 8 as that isn't really the goal here. Also if the user wants to force it in those browsers they can stick the separate code in  tags so it only loads on those browsers.
