### ISSUE TITLE
Android 

### ISSUE THREAD

**Issue by rsgd** [Abban/jQuery-Picture#11]
Great plugin!
But I expected that it is not working with Android.
Is that because of my complex setup within my project or isn’t there any Android support implemented yet?
Thanks.

**Comment by Abban** [comment]
I didn't test it on Android as I don't have a device but I assume it works ok. As long as js is turned on. Can you do a quick test of the demo on your device and let me know?

**Comment by rsgd** [comment]
Thanks for getting back to me. The demo does work on my device. But it 
uses the figure element and I went for the picture element. Is there a 
demo for that as well?

Am 12.11.12 11:15, schrieb Abban Dunne:

> I didn't test it on Android as I don't have a device but I assume it 
> works ok. As long as js is turned on. Can you do a quick test of the 
> demo on your device and let me know?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Abban/jQuery-Picture/issues/11#issuecomment-10282350. 

## 

---

Raffael Stüken

## Büro für Grafik Design

Ubierring 50

## 50678 Köln

+49(0)221 78964944

## +49(0)175 1640356

post@raffaelstueken.de

## www.raffaelstueken.de

**Comment by Abban** [comment]
Ahh, that would be the problem! Theres currently no support for picture in a lot of browsers as its not a valid html tag yet! I really only put it in there for messing about. You should really be using the figure tag for everything until the new tag is implemented.

**Comment by rsgd** [comment]
ah, ok, i see :)
Well for now I will need to decide if I want to go for the figure tag or 
if android is just not supported for this feature on my site.
Thanks again for your reply and that graet, great plugin!

Am 12.11.12 14:34, schrieb Abban Dunne:

> Ahh, that would be the problem! Theres currently no support for in a 
> lot of browsers as its not a valid html tag yet! I really only put it 
> in there for messing about. You should really be using the tag for 
> everything until the new tag is implemented.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Abban/jQuery-Picture/issues/11#issuecomment-10287389. 

## 

---

Raffael Stüken

## Büro für Grafik Design

Ubierring 50

## 50678 Köln

+49(0)221 78964944

## +49(0)175 1640356

post@raffaelstueken.de

## www.raffaelstueken.de
