### ISSUE TITLE
Replace <noscript> tag, rather than appending image

### ISSUE THREAD

**Issue by LucPestille** [Abban/jQuery-Picture#15]
I've got a more complex figure than the standard variety, and could do with the option (or set as default) for the script to _replace_ the noscript tag with the new image tag, rather than appending it to the end of the figure.

For example; I have a wrapper around the image which shows a zoom icon when you hover over it - with the current script, the image is placed outside of the wrapper and thus breaks the functionallity;

```
<figure class="responsive zoomhover" 
data-media="img_320.jpg" 
data-media480="img_480.jpg" 
data-media768="img_620.jpg"
data-media992="img_620.jpg">

<span class="zoomhover__wrapper">

  <a href="#"><noscript>
    <img src="img.jpg" alt="Hello" />
  </noscript></a>
  <a class="zoomhover__icon is-lowlight" href="#" title="View larger"><i class="icon-search"><span class="visuallyhidden">Zoom</span></i></a>

</span>

<figcaption class="zeta">Hello responsive!</figcaption>

</figure>
```

**Comment by LucPestille** [comment]
Just removing the noscript tag doesn't solve the problem - the new image is still just appended to the end of the figure element, rather than being a replacment for the noscript tag. Without doing that, there's no way to have anything but a basic figure > image structure...

**Comment by Abban** [comment]
$($el).picture({ insertElement: '>span >a' });

**Comment by LucPestille** [comment]
Perfect. Thanks for the updates.
