### ISSUE TITLE
Alt text is undefined

### ISSUE THREAD

**Issue by LucPestille** [Abban/jQuery-Picture#16]
Using the figure implementation, the alt attribute, set OK on the image within the noscript tag, is set as "undefined" when the new image is created/updated.

**Comment by LucPestille** [comment]
I still get undefined errors when using the alt attribute, because you've changed what it looks for to the _title_ attribute. That alone might throw some people off, but it doesn't work as is anyway...

**Comment by Abban** [comment]
This is because alt isn't a valid attribute for a figure tag. I'm looking at a demo of a figure with and without the title tag. In the figure with an alt is added to the img. In the figure without it adds nothing.

**Comment by LucPestille** [comment]
Ahh - I was adding the alt attribute to the img within the noscript tag - that's where I'd expect it to pull it from, since it's adding it back to the final image tag...
