### ISSUE TITLE
Safari Mobile on iPhone 5 not acting as expected

### ISSUE THREAD

**Issue by thoroughlydecent** [Abban/jQuery-Picture#17]
Hi, 

a quick one about the explanation text  - do you mean 440 rather than 400 - "with no number is for the 0-400 area"  as the next data-media is 440 . Not being  a pedant, just worried I'm missing something.

Cheers

**Comment by Abban** [comment]
Yeah in the example code theres:

``` html
    <figure data-media="images/small.png" data-media440="images/medium.png"
```

The 'data-media' image is served when the screen size is under 440, I need to update the copy! Thanks.
