### ISSUE TITLE
Link to images ?

### ISSUE THREAD

**Issue by hkamci** [Abban/jQuery-Picture#3]
First of all, thanks for this great script.

It's working very well.

My problem is how can I give a link to images ? I tried with data-link="" but it didn't work. Any suggestion?

Thanks....

**Comment by hkamci** [comment]
I'm asking it because I'm not sure which one is semantic?

<a href="#">

<figure>
....
</fiigure>
</a>

or 

<figure>
<a href="#">
...
</a>
</figure>


If first one is semantic, then no problem, but if second one is semantic than I can not use it with your script...

**Comment by hkamci** [comment]
<code>
&lt;figure&gt;
&lt;a href="#"&gt;...&lt;/a&gt;
&lt;/figure&gt;
</code>

or

&lt;a href="#"&gt;&lt;figure&gt;
...
&lt;/figure&gt;&lt;/a&gt;

**Comment by Abban** [comment]
Hmm, its perfectly acceptable to wrap links around block level elements in HTML5 but I've run into problems with it and IE.  Give me a minute to look at it and see if I can figure out a decent fix.

**Comment by Abban** [comment]
Ok, you can update the plugin now.

All you need to do is wrap the noscript tag with a link and it'll insert the img tag into that instead of directly inside the figure element. Wrapping the noscript ensures that it degrades gracefully.

**Comment by hkamci** [comment]
great!!!

Thanks for your work...
