### ISSUE TITLE
Lazy Load for images?

### ISSUE THREAD

**Issue by hkamci** [Abban/jQuery-Picture#5]
Hi again,

Is there any possibility to work with lazy load (http://www.appelsiini.net/projects/lazyload) script? It needs image dimensions (width and height) to work. Or if you know any other solution...

**Comment by Abban** [comment]
Howdy,

I guess the initial loading of the image could be delayed then called using a lazyload event. I'll look into it this evening.

**Comment by Abban** [comment]
I don't think I'm going to be able to make this compatible. To do so would add too much complication to the script which kind've defeats the purpose.

**Comment by hkamci** [comment]
No problem, thanks for your interest...
