### ISSUE TITLE
Retina Support

### ISSUE THREAD

**Issue by Abban** [Abban/jQuery-Picture#6]
Add support for pixel density somehow.

**Comment by artmsilva** [comment]
I agree.

**Comment by tinyearth** [comment]
So how does the retina support work exactly? I'm testing this on iPhone 4S using the picture tag, and its responding to 960 width instead of 480.

**Comment by Abban** [comment]
It just multiplies the width by the pixel density. You need to have a breakpoint in the tag set for the larger sizes then. TBH I never use this option, I just use the jpeg compression technique.
