### ISSUE TITLE
Add class to image

### ISSUE THREAD

**Issue by prestarocket** [Abban/jQuery-Picture#9]
Hello, 
firsr thx for your plugin...

How can i add a class to the image ?
EX :
'

``` html
<figure class="responsive" data-media="assets/images/small.png" data-media440="assets/images/medium.png" data-media600="assets/images/large.png" title="A Half Brained Idea">
        <img src="assets/images/large.png" alt="A Half Brained Idea" class="myclass">
</figure>
```

**Comment by Abban** [comment]
You can't directly add a class to the image directly, but you can add it to the parent figure:

``` html
<figure class="responsive my_class">
   <img>
</figure>
```

And select it like this:

``` javascript
$('.my_class img');
```

And this:

``` css
.my_class img{}
```

**Comment by prestarocket** [comment]
i would like to add the class in the img tag...

**Comment by prestarocket** [comment]
ok it fine i could do my job with your selector.
thx

**Comment by Abban** [comment]
Why straight to the image tag?

**Comment by prestarocket** [comment]
in order to use an another plugin but it s fine, i ll use your idea ('.class img')
